import { test } from 'node:test';
import assert from 'node:assert/strict';
import { MailService } from '../src/mail.js';
import { account, compose, temporaryStore, testImap } from './fixtures.js';
import { decodeRef, encodeRef } from '../src/types.js';

test('TLS IMAP search, read, attachments and multi-account isolation', { timeout: 120000 }, async t => {
  const composed = await compose({ subject: '中文报告', date: new Date('2026-10-07T09:00:00Z'), text: '中文正文。'.repeat(40), html: '<p>中文正文。</p>', attachments: [{ filename: '../../report.txt', content: '附件内容，仅按需下载', contentType: 'text/plain' }] });
  // This mock searches raw headers without RFC 2047 decoding; use an RFC 6532 UTF-8 subject.
  const firstMail = Buffer.from(composed.toString('utf8').replace(/^Subject: [^\r\n]*/m, 'Subject: 中文报告'));
  const oldMail = await compose({ subject: 'Old report', date: new Date('2026-10-01T09:00:00Z'), text: 'Older message' });
  const htmlMail = await compose({ subject: 'HTML only', date: new Date('2026-10-06T09:00:00Z'), html: '<h1>课程安排</h1><p>周五上课</p><img src="https://example.com/tracker"><script>window.attack=1</script>' });
  const a = await testImap([firstMail, oldMail, htmlMail]);
  const b = await testImap([await compose({ subject: '另一个邮箱的信', date: new Date('2026-10-08T09:00:00Z'), text: '另一份内容' })]);
  t.after(async () => { await a.close(); await b.close(); });
  const store = await temporaryStore();
  const one = await store.save(account(a.port));
  const two = await store.save(account(b.port, { name: '邮箱二', email: 'second@example.com' }));
  const service = new MailService(store, { ca: a.cert });
  assert.equal((await service.testConnection(one.id)).ok, true);
  assert.ok((await service.listFolders(one.id)).folders.some(f => f.path === 'INBOX'));
  const combined = await service.search({ limit: 2 });
  assert.equal(combined.total, 4); assert.equal(combined.messages.length, 2); assert.equal(combined.nextOffset, 2);
  assert.equal(combined.messages[0].accountId, two.id);
  const next = await service.search({ limit: 2, offset: 2 });
  assert.equal(next.messages.length, 2); assert.equal(next.nextOffset, null);
  assert.equal(new Set([...combined.messages, ...next.messages].map(m => m.ref)).size, 4);
  const found = await service.search({ accountId: one.id, subject: '中文', from: 'sender@example.com', unreadOnly: true, since: '2026-10-01', before: '2026-10-09' });
  assert.equal(found.total, 1);
  a.commands.length = 0;
  const message = await service.readMessage(found.messages[0].ref, 0, 10);
  assert.ok(message.body.text.includes('中文正文')); assert.equal(message.body.nextOffset, 10);
  assert.equal(message.attachments.length, 1);
  assert.ok(!a.commands.join('').toUpperCase().includes(`BODY.PEEK[${message.attachments[0].attachmentId}]`));
  const attachment = await service.attachment(found.messages[0].ref, message.attachments[0].attachmentId);
  assert.equal(attachment.data.toString('utf8'), '附件内容，仅按需下载');
  assert.equal((await service.search({ accountId: one.id, subject: '中文', unreadOnly: true })).total, 1);
  const html = await service.search({ accountId: one.id, subject: 'HTML only' });
  const body = (await service.readMessage(html.messages[0].ref)).body.text;
  assert.ok(body.includes('课程安排') && body.includes('周五上课'));
  assert.ok(!body.includes('window.attack') && !body.includes('<img'));
  const invalid = decodeRef(found.messages[0].ref); invalid.uidValidity = '9999';
  await assert.rejects(service.readMessage(encodeRef(invalid)), /重新搜索/);
  await store.save({ ...account(b.port, { id: two.id, name: '邮箱二', email: 'second@example.com' }), imap: { ...account(b.port).imap, password: 'wrong-password' } });
  const partial = await service.search({});
  assert.equal(partial.messages.length, 3); assert.equal(partial.errors.length, 1);
  assert.equal(partial.errors[0].accountId, two.id); assert.match(partial.errors[0].message, /登录失败/);
  await assert.rejects(new MailService(store).testConnection(one.id), /证书/);
});
